export const uniquePersons = [
    { name: "John", age: 23, gender: "male" },
    { name: "Jane", age: 45, gender: "female" },
    { name: "Sam", age: 34, gender: "male" },
    { name: "Alice", age: 27, gender: "female" },
    { name: "Bob", age: 51, gender: "male" },
    { name: "Eve", age: 38, gender: "female" },
    { name: "Tom", age: 30, gender: "male" },
    { name: "Lily", age: 29, gender: "female" },
    { name: "Jack", age: 36, gender: "male" },
    { name: "Olivia", age: 22, gender: "female" },
    { name: "Mike", age: 40, gender: "male" },
    { name: "Emma", age: 33, gender: "female" },
    { name: "Chris", age: 28, gender: "male" },
    { name: "Sophia", age: 26, gender: "female" },
    { name: "David", age: 48, gender: "male" },
    { name: "Mia", age: 31, gender: "female" },
    { name: "James", age: 41, gender: "male" },
    { name: "Isabella", age: 37, gender: "female" },
    { name: "Daniel", age: 25, gender: "male" },
    { name: "Ava", age: 39, gender: "female" },
    { name: "Michael", age: 35, gender: "male" },
    { name: "Charlotte", age: 24, gender: "female" },
    { name: "William", age: 46, gender: "male" },
    { name: "Amelia", age: 32, gender: "female" },
    { name: "Matthew", age: 50, gender: "male" },
    { name: "Harper", age: 42, gender: "female" },
    { name: "Joseph", age: 47, gender: "male" },
    { name: "Evelyn", age: 44, gender: "female" },
    { name: "Andrew", age: 49, gender: "male" },
    { name: "Abigail", age: 43, gender: "female" }
  ];

  